AddCSLuaFile("shared.lua")
AddCSLuaFile("sh_appbase.lua")
AddCSLuaFile("sh_panelos.lua")
AddCSLuaFile("mp/shared.lua")
AddCSLuaFile("mp/cl_init.lua")
AddCSLuaFile("cl_graphics.lua")
AddCSLuaFile("cl_init.lua")

include("shared.lua")
include("sh_appbase.lua")
include("sh_panelos.lua")
include("mp/shared.lua")